#!/bin/bash
# The Ceremony — Setup Script
# Installs deps, generates secrets, writes env files.
# Idempotent: re-running preserves existing secrets.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"

echo ""
echo "  The Ceremony — Setup"
echo "  ─────────────────────────────"
echo ""

# ── Phase 1: Install dependencies ──────────────────────────

echo "  [1/5] Dependencies"

if [ -d "$ROOT/web/node_modules" ]; then
  echo "        web/          ✓ already installed"
else
  echo "        web/          installing..."
  (cd "$ROOT/web" && npm install --silent)
  echo "        web/          ✓ done"
fi

if [ -d "$ROOT/keeper-service/node_modules" ]; then
  echo "        keeper-service/ ✓ already installed"
else
  echo "        keeper-service/ installing..."
  (cd "$ROOT/keeper-service" && npm install --silent)
  echo "        keeper-service/ ✓ done"
fi

echo "        rigging/      ✓ no deps"
echo ""

# ── Phase 2: Generate secrets ──────────────────────────────

echo "  [2/5] Secrets"

# Source existing root .env if present (preserves secrets across runs)
if [ -f "$ROOT/.env" ]; then
  set -a
  source "$ROOT/.env"
  set +a
  echo "        Found existing .env — keeping current secrets"
fi

changed=false

if [ -z "${CEREMONY_TOKEN_SECRET:-}" ]; then
  CEREMONY_TOKEN_SECRET=$(openssl rand -hex 32)
  echo "        CEREMONY_TOKEN_SECRET  generated"
  changed=true
else
  echo "        CEREMONY_TOKEN_SECRET  ✓ exists"
fi

if [ -z "${MC_SECRET:-}" ]; then
  MC_SECRET=$(openssl rand -hex 16)
  echo "        MC_SECRET              generated"
  changed=true
else
  echo "        MC_SECRET              ✓ exists"
fi

if [ -z "${KEEPER_SHARED_SECRET:-}" ]; then
  KEEPER_SHARED_SECRET=$(openssl rand -hex 32)
  echo "        KEEPER_SHARED_SECRET   generated"
  changed=true
else
  echo "        KEEPER_SHARED_SECRET   ✓ exists"
fi

echo ""

# ── Phase 3: API key (optional) ───────────────────────────

echo "  [3/5] Anthropic API Key"

# Check keeper-service/.env for existing key
ANTHROPIC_API_KEY=""
if [ -f "$ROOT/keeper-service/.env" ]; then
  existing_key=$(grep "^ANTHROPIC_API_KEY=" "$ROOT/keeper-service/.env" 2>/dev/null | cut -d= -f2- || true)
  if [ -n "$existing_key" ]; then
    ANTHROPIC_API_KEY="$existing_key"
    echo "        ✓ Key already configured in keeper-service/.env"
  fi
fi

if [ -z "$ANTHROPIC_API_KEY" ]; then
  echo "        No API key found. You can add one now for live mode,"
  echo "        or press Enter to skip (mock mode — no API costs)."
  echo ""
  echo -n "        Anthropic API key (or Enter to skip): "
  read -rs api_key
  echo ""

  if [ -n "$api_key" ]; then
    if [[ ! "$api_key" =~ ^sk-ant- ]]; then
      echo "        ⚠ Warning: key doesn't start with sk-ant-"
      echo "          (continuing anyway — you can fix it later)"
    fi
    ANTHROPIC_API_KEY="$api_key"
  fi
fi

# Determine mode
if [ -n "$ANTHROPIC_API_KEY" ]; then
  KEEPER_BACKEND="${KEEPER_BACKEND:-remote}"
  echo "        Mode: remote (live Claude API)"
else
  KEEPER_BACKEND="${KEEPER_BACKEND:-mock}"
  echo "        Mode: mock (no API calls)"
fi

echo ""

# ── Phase 4: Write env files ──────────────────────────────

echo "  [4/5] Writing env files"

# Root .env
cat > "$ROOT/.env" << EOF
# The Ceremony — Root Environment (generated by setup.sh)
CEREMONY_TOKEN_SECRET=${CEREMONY_TOKEN_SECRET}
MC_SECRET=${MC_SECRET}
KEEPER_SHARED_SECRET=${KEEPER_SHARED_SECRET}
KEEPER_BACKEND=${KEEPER_BACKEND}
EOF
echo "        .env                  ✓"

# keeper-service/.env
if [ -n "$ANTHROPIC_API_KEY" ]; then
  api_key_line="ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"
else
  api_key_line="# ANTHROPIC_API_KEY=sk-ant-..."
fi

cat > "$ROOT/keeper-service/.env" << EOF
# The Ceremony — Keeper Service (generated by setup.sh)
${api_key_line}

# Model and rate limits
KEEPER_MODEL=claude-haiku-4-5-20251001
KEEPER_MAX_TOKENS_PER_RESPONSE=1024
KEEPER_MAX_REQUESTS_PER_SESSION=100
KEEPER_MAX_REQUESTS_PER_MINUTE=10
KEEPER_PORT=3005

KEEPER_SHARED_SECRET=${KEEPER_SHARED_SECRET}
EOF
echo "        keeper-service/.env   ✓"

# web/.env.local
cat > "$ROOT/web/.env.local" << EOF
# The Ceremony — Web / Next.js (generated by setup.sh)
KEEPER_URL=http://localhost:3005
KEEPER_BACKEND=${KEEPER_BACKEND}

CEREMONY_TOKEN_SECRET=${CEREMONY_TOKEN_SECRET}
MC_SECRET=${MC_SECRET}
KEEPER_SHARED_SECRET=${KEEPER_SHARED_SECRET}
EOF
echo "        web/.env.local        ✓"

echo ""

# ── Phase 5: Summary ──────────────────────────────────────

echo "  [5/5] Summary"
echo "  ─────────────────────────────"
echo ""
echo "  Mode:       ${KEEPER_BACKEND}"
echo "  MC Secret:  ${MC_SECRET}"
echo "              (the MC needs this to log in)"
echo ""
echo "  Next steps:"
echo "    ./start.sh          Start all services via PM2"
echo "    cd web && npm run dev   Dev mode (hot reload)"
echo ""
echo "  Re-run this script any time — existing secrets are preserved."
echo ""
