#!/usr/bin/env node
// Builds story-matrix.html with inline data from config/story-matrix/*.json
// Run: node config/story-matrix/build-viz.js

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../..');
const HTML_PATH = path.join(ROOT, 'web/public/story-matrix.html');
const DATA_DIR = __dirname;

// Read the HTML template
let html = fs.readFileSync(HTML_PATH, 'utf8');

// Read data files
const dataFiles = ['s0', 's1', 's2', 's3', 's4'];
const lines = [];

for (const name of dataFiles) {
  const data = JSON.parse(fs.readFileSync(path.join(DATA_DIR, name + '.json'), 'utf8'));
  lines.push('var STORY_MATRIX_' + name.toUpperCase() + ' = ' + JSON.stringify(data) + ';');
}

const arcs = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'arcs.json'), 'utf8'));
lines.push('var STORY_MATRIX_ARCS = ' + JSON.stringify(arcs) + ';');

const dataBlock = '\n// ─── INLINE DATA (generated by build-viz.js) ───\n' + lines.join('\n') + '\n// ─── END INLINE DATA ───\n';

// Inject before the first <script> tag's content
const marker = '<script>\n// ─── CONSTANTS';
if (html.indexOf(marker) === -1) {
  console.error('Could not find injection marker in HTML');
  process.exit(1);
}

html = html.replace(marker, '<script>' + dataBlock + '\n// ─── CONSTANTS');

fs.writeFileSync(HTML_PATH, html);

const sizeKB = (Buffer.byteLength(html) / 1024).toFixed(1);
console.log('Built story-matrix.html with inline data (' + sizeKB + ' KB)');
